# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Variable 'BROWSER' was defined in the Variables tab
# Variable 'ROLE_GROUP' was defined in the Variables tab
trigger:
  branches:
    include:
    - refs/heads/Test_Execution
name: $(date:yyyyMMdd)$(rev:.r)
resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/Test_Execution
jobs:
- job: Job_1
  displayName: Build and Copy Artifacts
  cancelTimeoutInMinutes: 1
  pool:
    name: QE-Win10-iCargo
  steps:
  - checkout: self
    clean: true
    fetchTags: false
  - task: NuGetToolInstaller@0
    displayName: Use NuGet 6.0
    inputs:
      versionSpec: 6.0
  - task: NuGetCommand@2
    displayName: NuGet restore
    inputs:
      solution: '**\*.sln'
  - task: VSBuild@1
    displayName: Build solution
    inputs:
      platform: $(BuildPlatform)
      configuration: $(BuildConfiguration)
      clean: true
  - task: CopyFiles@2
    displayName: 'Copy Files to: Staging Directory'
    inputs:
      SourceFolder: $(Build.SourcesDirectory)
      TargetFolder: ' $(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: iCargoUIAutomation'
    inputs:
      ArtifactName: iCargoUIAutomation
- job: Job_2
  displayName: Execution job
  timeoutInMinutes: 240
  dependsOn: Job_1
  pool:
    name: QE-Win10-iCargo
  steps:
  - checkout: self
    clean: true
    fetchTags: false
  - task: PowerShell@2
    displayName: PowerShell Script
    inputs:
      targetType: inline
      script: >
        echo "Connecting to IGQW10ICGQE01"

        $Server="IGQW10ICGQE01"

        $User="Airgroup\iusr_qasvc"

        $Password="Q@svcUS3R!"

        cmdkey /generic:TERMSRV/$Server /user:$User /pass:$Password

        mstsc /v:$Server


        echo "Connecting to IGQW10ICGQE02"

        $Server="IGQW10ICGQE02"

        $User="Airgroup\iusr_qasvc"

        $Password="Q@svcUS3R!"

        cmdkey /generic:TERMSRV/$Server /user:$User /pass:$Password

        mstsc /v:$Server


        echo "Connecting to IGQW10ICGQE03"

        $Server="IGQW10ICGQE03"

        $User="Airgroup\iusr_qasvc"

        $Password="Q@svcUS3R!"

        cmdkey /generic:TERMSRV/$Server /user:$User /pass:$Password

        mstsc /v:$Server


        echo "Connecting to IGQW10ICGQE04"

        $Server="IGQW10ICGQE04"

        $User="Airgroup\iusr_qasvc"

        $Password="Q@svcUS3R!"

        cmdkey /generic:TERMSRV/$Server /user:$User /pass:$Password

        mstsc /v:$Server


        echo "Connecting to IGQW10ICGQE05"

        $Server="IGQW10ICGQE05"

        $User="Airgroup\iusr_qasvc"

        $Password="Q@svcUS3R!"

        cmdkey /generic:TERMSRV/$Server /user:$User /pass:$Password

        mstsc /v:$Server
  - task: DownloadBuildArtifacts@1
    displayName: Download Build Artifacts
    inputs:
      artifactName: iCargoUIAutomation
      extractTars: false
  - task: VSTest@3
    displayName: VsTest - testAssemblies
    inputs:
      testAssemblyVer2: >-
        **\iCargoUIAutomation.dll
         **\$(buildConfiguration)\*[Tt]est.dll
        **\$(buildConfiguration)\*test*.dll

        !**\*Microsoft.VisualStudio.TestPlatform*

        !**\obj\**
      searchFolder: $(System.ArtifactsDirectory)
      testFiltercriteria: TestCategory=CAP018_BKG_00001
      testRunTitle: iCargo.QA_$(Date:yyyyMMdd)
      rerunFailedTests: true
      rerunFailedThreshold: 91
...

