// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace iCargoUIAutomation.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("LTE001 Test Cases")]
    public partial class LTE001TestCasesFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "LTE001_Create a booking in LTE001 screen.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "LTE001 Test Cases", null, ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("LTE001_ACC_00001_Create a PP AWB in LTE001 for a known shipper")]
        [NUnit.Framework.CategoryAttribute("LTE001")]
        [NUnit.Framework.CategoryAttribute("LTE001_ACC_00001")]
        [NUnit.Framework.CategoryAttribute("smoke")]
        [NUnit.Framework.CategoryAttribute("DataSource:../TestData/LTE001_CreateShipment_TestData.xlsx")]
        [NUnit.Framework.CategoryAttribute("DataSet:LTE001_ACC_00001")]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "GEG", "SEA", "PRIORITY", "None", "NONSCR", "None", "None", "1", "100", "PP", "CREDIT", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00001", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "GEG", "SEA", "PRIORITY", "None", "NONSCR", "None", "None", "8", "600", "PP", "CREDIT", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00001", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "GEG", "SEA", "GENERAL", "None", "NONSCR", "None", "None", "20", "750", "PP", "CREDIT", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00001", null)]
        [NUnit.Framework.TestCaseAttribute("ASQXGUEST", "C1001", "", "10763", "SEA", "JFK", "GENERAL", "None", "NONSCR", "None", "None", "13", "775", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00002", null)]
        [NUnit.Framework.TestCaseAttribute("ASQXGUEST", "C1001", "", "10763", "SEA", "JFK", "PRIORITY", "None", "2199", "None", "None", "8", "360", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00002", null)]
        [NUnit.Framework.TestCaseAttribute("ASQXGUEST", "C1001", "", "10763", "SEA", "JFK", "GOLDSTREAK", "None", "NONSCR", "None", "None", "2", "59", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00002", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SEA", "LAX", "PRIORITY", "DGR", "NONSCR", "UN8000", "None", "1", "30", "PP", "CREDIT", "CART", "8000", "Consumer commodity", "Y963", "0.5", "No", "", "", "Yes", "LTE001_ACC_00003", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SEA", "ANC", "PRIORITY", "DGR", "NONSCR", "UN1845", "None", "2", "65", "PP", "CREDIT", "CART", "1845", "Dry ice", "954", "0.5", "No", "", "", "Yes", "LTE001_ACC_00003", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SEA", "HNL", "PRIORITY", "DGR", "NONSCR", "UN3110", "None", "3", "99", "PP", "CREDIT", "CART", "3110", "Organic peroxide type F, solid *", "570", "0.5", "No", "", "", "Yes", "LTE001_ACC_00003", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "ANC", "SEA", "PRIORITY", "None", "0300", "None", "None", "13", "775", "PP", "CREDIT", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00004", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SEA", "LAX", "PRIORITY", "None", "2199", "None", "None", "8", "360", "PP", "CREDIT", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00004", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SAN", "JFK", "PRIORITY", "None", "0666", "None", "None", "2", "55", "PP", "CREDIT", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00004", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "GEG", "SEA", "PRIORITY", "None", "NONSCR", "None", "None", "1", "100", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00005", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SAN", "JFK", "GOLDSTREAK", "None", "NONSCR", "None", "None", "8", "600", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00005", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "GEG", "SEA", "GENERAL", "None", "NONSCR", "None", "None", "20", "750", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00005", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "DFW", "SEA", "PRIORITY", "None", "NONSCR", "None", "None", "1", "100", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00005", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "DFW", "SEA", "GOLDSTREAK", "None", "NONSCR", "None", "None", "8", "600", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00005", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "DEN", "SEA", "GENERAL", "None", "NONSCR", "None", "None", "20", "750", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00005", null)]
        [NUnit.Framework.TestCaseAttribute("", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "DEN", "SEA", "GENERAL", "None", "NONSCR", "None", "None", "20", "750", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00007", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SEA", "JFK", "GENERAL", "None", "NONSCR", "None", "None", "18", "360", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00007", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SAN", "JFK", "GOLDSTREAK", "None", "NONSCR", "None", "None", "2", "55", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00007", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SEA", "LAX", "GENERAL", "None", "NONSCR", "None", "None", "2", "59", "PP", "CREDIT", "CART", "", "", "", "", "", "1", "", "Yes", "LTE001_ACC_00008", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SEA", "JFK", "PRIORITY", "None", "2199", "None", "None", "12", "324", "PP", "CREDIT", "CART", "", "", "", "", "", "1", "", "Yes", "LTE001_ACC_00008", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SEA", "LAX", "GENERAL", "None", "NONSCR", "None", "None", "13", "775", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00009", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SEA", "LAX", "PRIORITY", "None", "NONSCR", "None", "None", "6", "200", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00009", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SEA", "ANC", "PRIORITY", "None", "NONSCR", "None", "None", "8", "840", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00009", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SEA", "JFK", "GENERAL", "None", "NONSCR", "None", "None", "2", "59", "PP", "CREDIT", "CART", "", "", "", "", "", "PDX", "", "Yes", "LTE001_ACC_00010", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SEA", "LAX", "PRIORITY", "None", "2199", "None", "None", "36", "259", "PP", "CREDIT", "CART", "", "", "", "", "", "JFK", "", "Yes", "LTE001_ACC_00010", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "OTZ", "SEA", "GENERAL", "None", "0316", "None", "None", "13", "775", "PP", "CREDIT", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00011", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "OTZ", "SEA", "PRIORITY", "None", "2199", "None", "None", "8", "360", "PP", "CREDIT", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00011", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "OTZ", "SEA", "GOLDSTREAK", "None", "NONSCR", "None", "None", "2", "59", "PP", "CREDIT", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00011", null)]
        [NUnit.Framework.TestCaseAttribute("ASQXGUEST", "C1001", "", "10763", "SEA", "JFK", "GENERAL", "None", "NONSCR", "None", "None", "13", "775", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00012", null)]
        [NUnit.Framework.TestCaseAttribute("ASQXGUEST", "C1001", "", "10763", "SEA", "JFK", "PRIORITY", "None", "2199", "None", "None", "8", "360", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00012", null)]
        [NUnit.Framework.TestCaseAttribute("ASQXGUEST", "C1001", "", "10763", "SEA", "JFK", "GOLDSTREAK", "None", "NONSCR", "None", "None", "2", "59", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00012", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SEA", "ANC", "PRIORITY", "DGR,CAO", "NONSCR", "UN1170", "None", "1", "35", "CC", "None", "CART", "1170", "Ethanol", "364", "0.5", "No", "", "", "Yes", "LTE001_ACC_00015", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SEA", "ANC", "PRIORITY", "DGR,CAO", "NONSCR", "UN3480", "None", "76", "456", "CC", "None", "CART", "3090", "Lithium metal batteries", "968", "0.5", "No", "", "", "Yes", "LTE001_ACC_00015", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SEA", "ANC", "PRIORITY", "DGR,CAO", "NONSCR", " UN3480", "None", "56", "230", "CC", "None", "CART", "1075", "Petroleum gases, liquefied", "200", "0.5", "No", "", "", "Yes", "LTE001_ACC_00015", null)]
        [NUnit.Framework.TestCaseAttribute("ASQXGUEST", "", "11377", "10763", "SEA", "ANC", "Employee Shipment", "SAL", "NONSCR", "None", "None", "3", "87", "CC", "PP", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00016", null)]
        [NUnit.Framework.TestCaseAttribute("ASQXGUEST", "", "COMATJJ", "COMATFF", "SEA", "LAX", "COMAT", "COM", "NONSCR", "None", "COMAT", "2", "59", "PP", "NONE", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00017", null)]
        [NUnit.Framework.TestCaseAttribute("ASQXGUEST", "", "COMATJJ", "COMATFF", "SAN", "JFK", "COMAT", "COM", "NONSCR", "None", "COMAT", "2", "59", "PP", "NONE", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00017", null)]
        [NUnit.Framework.TestCaseAttribute("ASQXGUEST", "C1001", "", "10763", "SEA", "ANC", "GOLDSTREAK", "SAL", "NONSCR", "None", "None", "3", "87", "PP", "CREDIT", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00019", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SEA", "JFK", "GENERAL", "None", "NONSCR", "None", "None", "2", "59", "CC", "None", "CART", "", "", "", "", "", "PDX", "", "Yes", "LTE001_ACC_00021", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SEA", "LAX", "PRIORITY", "None", "2199", "None", "None", "36", "259", "CC", "None", "CART", "", "", "", "", "", "JFK", "", "Yes", "LTE001_ACC_00021", null)]
        [NUnit.Framework.TestCaseAttribute("ASQXGUEST", "C1001", "", "10763", "SEA", "ANC", "GENERAL", "None", "NONSCR", "None", "None", "13", "775", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00023", null)]
        [NUnit.Framework.TestCaseAttribute("ASQXGUEST", "C1001", "", "10763", "KTN", "ANC", "GENERAL", "None", "NONSCR", "None", "None", "13", "775", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00024", null)]
        [NUnit.Framework.TestCaseAttribute("ASQXGUEST", "C1001", "", "10763", "KTN", "ANC", "PRIORITY", "None", "2199", "None", "None", "8", "360", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00024", null)]
        [NUnit.Framework.TestCaseAttribute("ASQXGUEST", "C1001", "", "10763", "KTN", "ANC", "GOLDSTREAK", "None", "NONSCR", "None", "None", "2", "59", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00024", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SEA", "DEN", "GENERAL", "None", "NONSCR", "None", "None", "13", "775", "PP", "CREDIT", "CART", "", "", "", "", "", "", "10763", "Yes", "LTE001_ACC_00028", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11029", "10757", "SEA", "ANC", "PRIORITY", "None", "2300", "None", "None", "5", "250", "PP", "CREDIT", "CART", "", "", "", "", "", "", "10763", "Yes", "LTE001_ACC_00028", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "DFW", "SEA", "PRIORITY", "None", "NONSCR", "None", "None", "1", "100", "PP", "CREDIT", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00001", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "DFW", "SEA", "GOLDSTREAK", "None", "NONSCR", "None", "None", "8", "600", "PP", "CREDIT", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00001", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "DEN", "SEA", "GENERAL", "None", "NONSCR", "None", "None", "20", "750", "PP", "CREDIT", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00001", null)]
        [NUnit.Framework.TestCaseAttribute("ASQXGUEST", "C1001", "", "10763", "GEG", "SEA", "PRIORITY", "None", "NONSCR", "None", "None", "13", "775", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00002", null)]
        [NUnit.Framework.TestCaseAttribute("ASQXGUEST", "C1001", "", "10763", "SAN", "JFK", "GOLDSTREAK", "None", "NONSCR", "None", "None", "8", "360", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00002", null)]
        [NUnit.Framework.TestCaseAttribute("ASQXGUEST", "C1001", "", "10763", "GEG", "SEA", "GENERAL", "None", "NONSCR", "None", "None", "2", "59", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00002", null)]
        [NUnit.Framework.TestCaseAttribute("ASQXGUEST", "C1001", "", "10763", "DFW", "SEA", "PRIORITY", "None", "NONSCR", "None", "None", "13", "775", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00002", null)]
        [NUnit.Framework.TestCaseAttribute("ASQXGUEST", "C1001", "", "10763", "DFW", "SEA", "GOLDSTREAK", "None", "NONSCR", "None", "None", "8", "360", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00002", null)]
        [NUnit.Framework.TestCaseAttribute("ASQXGUEST", "C1001", "", "10763", "DEN", "SEA", "GENERAL", "None", "NONSCR", "None", "None", "2", "59", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00002", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SEA", "LAX", "PRIORITY", "DGR", "NONSCR", "UN2807", "None", "1", "30", "CC", "None", "CART", "2807", "Magnetized material", "953", "0.5", "No", "", "", "Yes", "LTE001_ACC_00003", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SAN", "JFK", "PRIORITY", "DGR", "NONSCR", "UN1977", "None", "2", "65", "CC", "None", "CART", "1977", "Nitrogen, refrigerated liquid", "202", "0.5", "No", "", "", "Yes", "LTE001_ACC_00003", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SAN", "JFK", "PRIORITY", "DGR", "NONSCR", "UN1760", "None", "3", "99", "CC", "None", "CART", "1760", "Corrosive liquid n.o.s. *", "850", "0.5", "No", "", "", "Yes", "LTE001_ACC_00003", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SAN", "JFK", "PRIORITY", "DGR", "NONSCR", "UN3373", "None", "1", "30", "CC", "None", "CART", "3373", "Biological substance, Category B", "650", "0.5", "No", "", "", "Yes", "LTE001_ACC_00003", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SAN", "JFK", "PRIORITY", "DGR", "NONSCR", "UN1993", "None", "2", "65", "CC", "None", "CART", "1993", "Flammable liquid n.o.s. *", "351", "0.5", "No", "", "", "Yes", "LTE001_ACC_00003", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SAN", "JFK", "PRIORITY", "DGR", "NONSCR", "UN1324", "None", "3", "99", "CC", "None", "CART", "1324", "Films, nitrocellulose base", "Y454", "0.5", "No", "", "", "Yes", "LTE001_ACC_00003", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SEA", "LAX", "PRIORITY", "DGR", "NONSCR", "UN3481", "None", "1", "30", "CC", "None", "CART", "3481", "Lithium ion batteries contained in equipment", "967", "0.5", "No", "", "", "Yes", "LTE001_ACC_00003", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SEA", "ANC", "PRIORITY", "DGR", "NONSCR", "UN3287", "None", "2", "65", "CC", "None", "CART", "3287", "Toxic liquid, inorganic n.o.s. *", "652", "0.5", "No", "", "", "Yes", "LTE001_ACC_00003", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SEA", "HNL", "PRIORITY", "DGR", "NONSCR", "UN1369", "None", "3", "99", "CC", "None", "CART", "1369", "p-Nitrosodimethylaniline", "467", "0.5", "No", "", "", "Yes", "LTE001_ACC_00003", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "DFW", "SEA", "PRIORITY", "DGR", "NONSCR", "UN8000", "None", "1", "30", "PP", "CREDIT", "CART", "8000", "Consumer commodity", "Y963", "0.5", "No", "", "", "Yes", "LTE001_ACC_00003", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "DFW", "SEA", "PRIORITY", "DGR", "NONSCR", "UN1845", "None", "2", "65", "PP", "CREDIT", "CART", "1845", "Dry ice", "954", "0.5", "No", "", "", "Yes", "LTE001_ACC_00003", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "DFW", "SEA", "PRIORITY", "DGR", "NONSCR", "UN3110", "None", "3", "99", "PP", "CREDIT", "CART", "3110", "Organic peroxide type F, solid *", "570", "0.5", "No", "", "", "Yes", "LTE001_ACC_00003", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "DFW", "SEA", "PRIORITY", "DGR", "NONSCR", "UN2807", "None", "1", "30", "CC", "None", "CART", "2807", "Magnetized material", "953", "0.5", "No", "", "", "Yes", "LTE001_ACC_00003", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "DFW", "SEA", "PRIORITY", "DGR", "NONSCR", "UN1977", "None", "2", "65", "CC", "None", "CART", "1977", "Nitrogen, refrigerated liquid", "202", "0.5", "No", "", "", "Yes", "LTE001_ACC_00003", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "DFW", "SEA", "PRIORITY", "DGR", "NONSCR", "UN1760", "None", "3", "99", "CC", "None", "CART", "1760", "Corrosive liquid n.o.s. *", "850", "0.5", "No", "", "", "Yes", "LTE001_ACC_00003", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "DEN", "SEA", "PRIORITY", "DGR", "NONSCR", "UN3373", "None", "1", "30", "CC", "None", "CART", "3373", "Biological substance, Category B", "650", "0.5", "No", "", "", "Yes", "LTE001_ACC_00003", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "DEN", "SEA", "PRIORITY", "DGR", "NONSCR", "UN1993", "None", "2", "65", "CC", "None", "CART", "1993", "Flammable liquid n.o.s. *", "351", "0.5", "No", "", "", "Yes", "LTE001_ACC_00003", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "DEN", "SEA", "PRIORITY", "DGR", "NONSCR", "UN1324", "None", "3", "99", "CC", "None", "CART", "1324", "Films, nitrocellulose base", "Y454", "0.5", "No", "", "", "Yes", "LTE001_ACC_00003", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "DEN", "SEA", "PRIORITY", "DGR", "NONSCR", "UN3481", "None", "1", "30", "CC", "None", "CART", "3481", "Lithium ion batteries contained in equipment", "967", "0.5", "No", "", "", "Yes", "LTE001_ACC_00003", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "DEN", "SEA", "PRIORITY", "DGR", "NONSCR", "UN3287", "None", "2", "65", "CC", "None", "CART", "3287", "Toxic liquid, inorganic n.o.s. *", "652", "0.5", "No", "", "", "Yes", "LTE001_ACC_00003", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "DEN", "SEA", "PRIORITY", "DGR", "NONSCR", "UN1369", "None", "3", "99", "CC", "None", "CART", "1369", "p-Nitrosodimethylaniline", "467", "0.5", "No", "", "", "Yes", "LTE001_ACC_00003", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "DFW", "SEA", "GENERAL", "None", "NONSCR", "None", "None", "13", "775", "PP", "CREDIT", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00004", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "DEN", "SEA", "PRIORITY", "None", "NONSCR", "None", "None", "8", "360", "PP", "CREDIT", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00004", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "DEN", "SEA", "GOLDSTREAK", "None", "NONSCR", "None", "None", "2", "55", "PP", "CREDIT", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00004", null)]
        [NUnit.Framework.TestCaseAttribute("", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00004", null)]
        public void LTE001_ACC_00001_CreateAPPAWBInLTE001ForAKnownShipper(
                    string agentCode, 
                    string unknownShipperCode, 
                    string shipperCode, 
                    string consigneeCode, 
                    string origin, 
                    string destination, 
                    string productCode, 
                    string sCC, 
                    string commodity, 
                    string shipmentDescription, 
                    string serviceCargoClass, 
                    string piece, 
                    string weight, 
                    string chargeType, 
                    string modeOfPayment, 
                    string cartType, 
                    string uNID, 
                    string properShipmentName, 
                    string packingInstruction, 
                    string netQtyPerPkg, 
                    string reportableQnty, 
                    string updatedValue, 
                    string ratedCustomer, 
                    string execute, 
                    string tags, 
                    string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "LTE001",
                    "LTE001_ACC_00001",
                    "smoke",
                    "DataSource:../TestData/LTE001_CreateShipment_TestData.xlsx",
                    "DataSet:LTE001_ACC_00001"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("AgentCode", agentCode);
            argumentsOfScenario.Add("UnknownShipperCode", unknownShipperCode);
            argumentsOfScenario.Add("ShipperCode", shipperCode);
            argumentsOfScenario.Add("ConsigneeCode", consigneeCode);
            argumentsOfScenario.Add("Origin", origin);
            argumentsOfScenario.Add("Destination", destination);
            argumentsOfScenario.Add("ProductCode", productCode);
            argumentsOfScenario.Add("SCC", sCC);
            argumentsOfScenario.Add("Commodity", commodity);
            argumentsOfScenario.Add("ShipmentDescription", shipmentDescription);
            argumentsOfScenario.Add("ServiceCargoClass", serviceCargoClass);
            argumentsOfScenario.Add("Piece", piece);
            argumentsOfScenario.Add("Weight", weight);
            argumentsOfScenario.Add("ChargeType", chargeType);
            argumentsOfScenario.Add("ModeOfPayment", modeOfPayment);
            argumentsOfScenario.Add("cartType", cartType);
            argumentsOfScenario.Add("UNID", uNID);
            argumentsOfScenario.Add("ProperShipmentName", properShipmentName);
            argumentsOfScenario.Add("PackingInstruction", packingInstruction);
            argumentsOfScenario.Add("NetQtyPerPkg", netQtyPerPkg);
            argumentsOfScenario.Add("ReportableQnty", reportableQnty);
            argumentsOfScenario.Add("UpdatedValue", updatedValue);
            argumentsOfScenario.Add("RatedCustomer", ratedCustomer);
            argumentsOfScenario.Add("Execute", execute);
            argumentsOfScenario.Add("Tags", tags);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("LTE001_ACC_00001_Create a PP AWB in LTE001 for a known shipper", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 4
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
 testRunner.Given(string.Format("User wants to execute the example \"{0}\" for the scenario \"{1}\"", execute, tags), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 6
 testRunner.When(string.Format("User switches station if BaseStation other than \"{0}\"", origin), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 7
 testRunner.And("User enters the screen name as \'LTE001\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 8
 testRunner.Then("User enters into the  iCargo \'Create Shipment\' page successfully", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 9
 testRunner.When("user clicks on the List button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 10
 testRunner.And(string.Format("User enters the Participant details with AgentCode \"{0}\", ShipperCode \"{1}\", Cons" +
                            "igneeCode \"{2}\"", agentCode, shipperCode, consigneeCode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 11
 testRunner.And("User clicks on the ContinueParticipant button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 12
 testRunner.And("User enters the Certificate details", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 13
 testRunner.And("User clicks on the ContinueCertificate button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 14
 testRunner.And(string.Format("User enters the Shipment details with Origin \"{0}\", Destination \"{1}\", ProductCod" +
                            "e \"{2}\", SCCCode \"{3}\", Commodity \"{4}\", ShipmentDescription\"{5}\", ServiceCargoC" +
                            "lass \"{6}\", Piece \"{7}\", Weight \"{8}\"", origin, destination, productCode, sCC, commodity, shipmentDescription, serviceCargoClass, piece, weight), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 15
 testRunner.And("User clicks on the ContinueShipment button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 16
 testRunner.And("User clicks on the Select Flight Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 17
 testRunner.And("User selects an \"Combination\" flight", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 18
 testRunner.And("User clicks on the ContinueFlightDetails button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 19
 testRunner.And(string.Format("User enters the Charge details with ChargeType \"{0}\" and ModeOfPayment \"{1}\"", chargeType, modeOfPayment), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 20
 testRunner.And("User clicks on the CalculateCharges button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 21
 testRunner.And("User clicks on the ContinueChargeDetails button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 22
 testRunner.And("User enters the Acceptance details", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 23
 testRunner.And("User clicks on the ContinueAcceptanceDetails button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 24
 testRunner.And("User enters the Screening details for row 1 with screeingMethod as \'Transfer Mani" +
                        "fest Verified\' and ScreeningResult as \'Pass\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 25
 testRunner.And("User clicks on the ContinueScreeningDetails button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 26
 testRunner.And("User checks the AWB_Verified checkbox", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 27
 testRunner.And("User saves all the details & handles all the popups", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("LTE001_ACC_00002_Create an AWB in LTE001 for an unknown shipper on a restricted p" +
            "ax flight")]
        [NUnit.Framework.CategoryAttribute("LTE001")]
        [NUnit.Framework.CategoryAttribute("LTE001_ACC_00002")]
        [NUnit.Framework.CategoryAttribute("smoke")]
        [NUnit.Framework.CategoryAttribute("DataSource:../TestData/LTE001_CreateShipment_TestData.xlsx")]
        [NUnit.Framework.CategoryAttribute("DataSet:LTE001_ACC_00001")]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "GEG", "SEA", "PRIORITY", "None", "NONSCR", "None", "None", "1", "100", "PP", "CREDIT", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00001", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "GEG", "SEA", "PRIORITY", "None", "NONSCR", "None", "None", "8", "600", "PP", "CREDIT", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00001", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "GEG", "SEA", "GENERAL", "None", "NONSCR", "None", "None", "20", "750", "PP", "CREDIT", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00001", null)]
        [NUnit.Framework.TestCaseAttribute("ASQXGUEST", "C1001", "", "10763", "SEA", "JFK", "GENERAL", "None", "NONSCR", "None", "None", "13", "775", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00002", null)]
        [NUnit.Framework.TestCaseAttribute("ASQXGUEST", "C1001", "", "10763", "SEA", "JFK", "PRIORITY", "None", "2199", "None", "None", "8", "360", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00002", null)]
        [NUnit.Framework.TestCaseAttribute("ASQXGUEST", "C1001", "", "10763", "SEA", "JFK", "GOLDSTREAK", "None", "NONSCR", "None", "None", "2", "59", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00002", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SEA", "LAX", "PRIORITY", "DGR", "NONSCR", "UN8000", "None", "1", "30", "PP", "CREDIT", "CART", "8000", "Consumer commodity", "Y963", "0.5", "No", "", "", "Yes", "LTE001_ACC_00003", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SEA", "ANC", "PRIORITY", "DGR", "NONSCR", "UN1845", "None", "2", "65", "PP", "CREDIT", "CART", "1845", "Dry ice", "954", "0.5", "No", "", "", "Yes", "LTE001_ACC_00003", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SEA", "HNL", "PRIORITY", "DGR", "NONSCR", "UN3110", "None", "3", "99", "PP", "CREDIT", "CART", "3110", "Organic peroxide type F, solid *", "570", "0.5", "No", "", "", "Yes", "LTE001_ACC_00003", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "ANC", "SEA", "PRIORITY", "None", "0300", "None", "None", "13", "775", "PP", "CREDIT", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00004", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SEA", "LAX", "PRIORITY", "None", "2199", "None", "None", "8", "360", "PP", "CREDIT", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00004", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SAN", "JFK", "PRIORITY", "None", "0666", "None", "None", "2", "55", "PP", "CREDIT", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00004", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "GEG", "SEA", "PRIORITY", "None", "NONSCR", "None", "None", "1", "100", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00005", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SAN", "JFK", "GOLDSTREAK", "None", "NONSCR", "None", "None", "8", "600", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00005", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "GEG", "SEA", "GENERAL", "None", "NONSCR", "None", "None", "20", "750", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00005", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "DFW", "SEA", "PRIORITY", "None", "NONSCR", "None", "None", "1", "100", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00005", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "DFW", "SEA", "GOLDSTREAK", "None", "NONSCR", "None", "None", "8", "600", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00005", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "DEN", "SEA", "GENERAL", "None", "NONSCR", "None", "None", "20", "750", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00005", null)]
        [NUnit.Framework.TestCaseAttribute("", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "DEN", "SEA", "GENERAL", "None", "NONSCR", "None", "None", "20", "750", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00007", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SEA", "JFK", "GENERAL", "None", "NONSCR", "None", "None", "18", "360", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00007", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SAN", "JFK", "GOLDSTREAK", "None", "NONSCR", "None", "None", "2", "55", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00007", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SEA", "LAX", "GENERAL", "None", "NONSCR", "None", "None", "2", "59", "PP", "CREDIT", "CART", "", "", "", "", "", "1", "", "Yes", "LTE001_ACC_00008", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SEA", "JFK", "PRIORITY", "None", "2199", "None", "None", "12", "324", "PP", "CREDIT", "CART", "", "", "", "", "", "1", "", "Yes", "LTE001_ACC_00008", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SEA", "LAX", "GENERAL", "None", "NONSCR", "None", "None", "13", "775", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00009", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SEA", "LAX", "PRIORITY", "None", "NONSCR", "None", "None", "6", "200", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00009", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SEA", "ANC", "PRIORITY", "None", "NONSCR", "None", "None", "8", "840", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00009", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SEA", "JFK", "GENERAL", "None", "NONSCR", "None", "None", "2", "59", "PP", "CREDIT", "CART", "", "", "", "", "", "PDX", "", "Yes", "LTE001_ACC_00010", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SEA", "LAX", "PRIORITY", "None", "2199", "None", "None", "36", "259", "PP", "CREDIT", "CART", "", "", "", "", "", "JFK", "", "Yes", "LTE001_ACC_00010", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "OTZ", "SEA", "GENERAL", "None", "0316", "None", "None", "13", "775", "PP", "CREDIT", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00011", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "OTZ", "SEA", "PRIORITY", "None", "2199", "None", "None", "8", "360", "PP", "CREDIT", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00011", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "OTZ", "SEA", "GOLDSTREAK", "None", "NONSCR", "None", "None", "2", "59", "PP", "CREDIT", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00011", null)]
        [NUnit.Framework.TestCaseAttribute("ASQXGUEST", "C1001", "", "10763", "SEA", "JFK", "GENERAL", "None", "NONSCR", "None", "None", "13", "775", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00012", null)]
        [NUnit.Framework.TestCaseAttribute("ASQXGUEST", "C1001", "", "10763", "SEA", "JFK", "PRIORITY", "None", "2199", "None", "None", "8", "360", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00012", null)]
        [NUnit.Framework.TestCaseAttribute("ASQXGUEST", "C1001", "", "10763", "SEA", "JFK", "GOLDSTREAK", "None", "NONSCR", "None", "None", "2", "59", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00012", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SEA", "ANC", "PRIORITY", "DGR,CAO", "NONSCR", "UN1170", "None", "1", "35", "CC", "None", "CART", "1170", "Ethanol", "364", "0.5", "No", "", "", "Yes", "LTE001_ACC_00015", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SEA", "ANC", "PRIORITY", "DGR,CAO", "NONSCR", "UN3480", "None", "76", "456", "CC", "None", "CART", "3090", "Lithium metal batteries", "968", "0.5", "No", "", "", "Yes", "LTE001_ACC_00015", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SEA", "ANC", "PRIORITY", "DGR,CAO", "NONSCR", " UN3480", "None", "56", "230", "CC", "None", "CART", "1075", "Petroleum gases, liquefied", "200", "0.5", "No", "", "", "Yes", "LTE001_ACC_00015", null)]
        [NUnit.Framework.TestCaseAttribute("ASQXGUEST", "", "11377", "10763", "SEA", "ANC", "Employee Shipment", "SAL", "NONSCR", "None", "None", "3", "87", "CC", "PP", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00016", null)]
        [NUnit.Framework.TestCaseAttribute("ASQXGUEST", "", "COMATJJ", "COMATFF", "SEA", "LAX", "COMAT", "COM", "NONSCR", "None", "COMAT", "2", "59", "PP", "NONE", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00017", null)]
        [NUnit.Framework.TestCaseAttribute("ASQXGUEST", "", "COMATJJ", "COMATFF", "SAN", "JFK", "COMAT", "COM", "NONSCR", "None", "COMAT", "2", "59", "PP", "NONE", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00017", null)]
        [NUnit.Framework.TestCaseAttribute("ASQXGUEST", "C1001", "", "10763", "SEA", "ANC", "GOLDSTREAK", "SAL", "NONSCR", "None", "None", "3", "87", "PP", "CREDIT", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00019", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SEA", "JFK", "GENERAL", "None", "NONSCR", "None", "None", "2", "59", "CC", "None", "CART", "", "", "", "", "", "PDX", "", "Yes", "LTE001_ACC_00021", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SEA", "LAX", "PRIORITY", "None", "2199", "None", "None", "36", "259", "CC", "None", "CART", "", "", "", "", "", "JFK", "", "Yes", "LTE001_ACC_00021", null)]
        [NUnit.Framework.TestCaseAttribute("ASQXGUEST", "C1001", "", "10763", "SEA", "ANC", "GENERAL", "None", "NONSCR", "None", "None", "13", "775", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00023", null)]
        [NUnit.Framework.TestCaseAttribute("ASQXGUEST", "C1001", "", "10763", "KTN", "ANC", "GENERAL", "None", "NONSCR", "None", "None", "13", "775", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00024", null)]
        [NUnit.Framework.TestCaseAttribute("ASQXGUEST", "C1001", "", "10763", "KTN", "ANC", "PRIORITY", "None", "2199", "None", "None", "8", "360", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00024", null)]
        [NUnit.Framework.TestCaseAttribute("ASQXGUEST", "C1001", "", "10763", "KTN", "ANC", "GOLDSTREAK", "None", "NONSCR", "None", "None", "2", "59", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00024", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SEA", "DEN", "GENERAL", "None", "NONSCR", "None", "None", "13", "775", "PP", "CREDIT", "CART", "", "", "", "", "", "", "10763", "Yes", "LTE001_ACC_00028", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11029", "10757", "SEA", "ANC", "PRIORITY", "None", "2300", "None", "None", "5", "250", "PP", "CREDIT", "CART", "", "", "", "", "", "", "10763", "Yes", "LTE001_ACC_00028", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "DFW", "SEA", "PRIORITY", "None", "NONSCR", "None", "None", "1", "100", "PP", "CREDIT", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00001", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "DFW", "SEA", "GOLDSTREAK", "None", "NONSCR", "None", "None", "8", "600", "PP", "CREDIT", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00001", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "DEN", "SEA", "GENERAL", "None", "NONSCR", "None", "None", "20", "750", "PP", "CREDIT", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00001", null)]
        [NUnit.Framework.TestCaseAttribute("ASQXGUEST", "C1001", "", "10763", "GEG", "SEA", "PRIORITY", "None", "NONSCR", "None", "None", "13", "775", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00002", null)]
        [NUnit.Framework.TestCaseAttribute("ASQXGUEST", "C1001", "", "10763", "SAN", "JFK", "GOLDSTREAK", "None", "NONSCR", "None", "None", "8", "360", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00002", null)]
        [NUnit.Framework.TestCaseAttribute("ASQXGUEST", "C1001", "", "10763", "GEG", "SEA", "GENERAL", "None", "NONSCR", "None", "None", "2", "59", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00002", null)]
        [NUnit.Framework.TestCaseAttribute("ASQXGUEST", "C1001", "", "10763", "DFW", "SEA", "PRIORITY", "None", "NONSCR", "None", "None", "13", "775", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00002", null)]
        [NUnit.Framework.TestCaseAttribute("ASQXGUEST", "C1001", "", "10763", "DFW", "SEA", "GOLDSTREAK", "None", "NONSCR", "None", "None", "8", "360", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00002", null)]
        [NUnit.Framework.TestCaseAttribute("ASQXGUEST", "C1001", "", "10763", "DEN", "SEA", "GENERAL", "None", "NONSCR", "None", "None", "2", "59", "CC", "None", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00002", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SEA", "LAX", "PRIORITY", "DGR", "NONSCR", "UN2807", "None", "1", "30", "CC", "None", "CART", "2807", "Magnetized material", "953", "0.5", "No", "", "", "Yes", "LTE001_ACC_00003", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SAN", "JFK", "PRIORITY", "DGR", "NONSCR", "UN1977", "None", "2", "65", "CC", "None", "CART", "1977", "Nitrogen, refrigerated liquid", "202", "0.5", "No", "", "", "Yes", "LTE001_ACC_00003", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SAN", "JFK", "PRIORITY", "DGR", "NONSCR", "UN1760", "None", "3", "99", "CC", "None", "CART", "1760", "Corrosive liquid n.o.s. *", "850", "0.5", "No", "", "", "Yes", "LTE001_ACC_00003", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SAN", "JFK", "PRIORITY", "DGR", "NONSCR", "UN3373", "None", "1", "30", "CC", "None", "CART", "3373", "Biological substance, Category B", "650", "0.5", "No", "", "", "Yes", "LTE001_ACC_00003", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SAN", "JFK", "PRIORITY", "DGR", "NONSCR", "UN1993", "None", "2", "65", "CC", "None", "CART", "1993", "Flammable liquid n.o.s. *", "351", "0.5", "No", "", "", "Yes", "LTE001_ACC_00003", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SAN", "JFK", "PRIORITY", "DGR", "NONSCR", "UN1324", "None", "3", "99", "CC", "None", "CART", "1324", "Films, nitrocellulose base", "Y454", "0.5", "No", "", "", "Yes", "LTE001_ACC_00003", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SEA", "LAX", "PRIORITY", "DGR", "NONSCR", "UN3481", "None", "1", "30", "CC", "None", "CART", "3481", "Lithium ion batteries contained in equipment", "967", "0.5", "No", "", "", "Yes", "LTE001_ACC_00003", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SEA", "ANC", "PRIORITY", "DGR", "NONSCR", "UN3287", "None", "2", "65", "CC", "None", "CART", "3287", "Toxic liquid, inorganic n.o.s. *", "652", "0.5", "No", "", "", "Yes", "LTE001_ACC_00003", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "SEA", "HNL", "PRIORITY", "DGR", "NONSCR", "UN1369", "None", "3", "99", "CC", "None", "CART", "1369", "p-Nitrosodimethylaniline", "467", "0.5", "No", "", "", "Yes", "LTE001_ACC_00003", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "DFW", "SEA", "PRIORITY", "DGR", "NONSCR", "UN8000", "None", "1", "30", "PP", "CREDIT", "CART", "8000", "Consumer commodity", "Y963", "0.5", "No", "", "", "Yes", "LTE001_ACC_00003", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "DFW", "SEA", "PRIORITY", "DGR", "NONSCR", "UN1845", "None", "2", "65", "PP", "CREDIT", "CART", "1845", "Dry ice", "954", "0.5", "No", "", "", "Yes", "LTE001_ACC_00003", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "DFW", "SEA", "PRIORITY", "DGR", "NONSCR", "UN3110", "None", "3", "99", "PP", "CREDIT", "CART", "3110", "Organic peroxide type F, solid *", "570", "0.5", "No", "", "", "Yes", "LTE001_ACC_00003", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "DFW", "SEA", "PRIORITY", "DGR", "NONSCR", "UN2807", "None", "1", "30", "CC", "None", "CART", "2807", "Magnetized material", "953", "0.5", "No", "", "", "Yes", "LTE001_ACC_00003", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "DFW", "SEA", "PRIORITY", "DGR", "NONSCR", "UN1977", "None", "2", "65", "CC", "None", "CART", "1977", "Nitrogen, refrigerated liquid", "202", "0.5", "No", "", "", "Yes", "LTE001_ACC_00003", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "DFW", "SEA", "PRIORITY", "DGR", "NONSCR", "UN1760", "None", "3", "99", "CC", "None", "CART", "1760", "Corrosive liquid n.o.s. *", "850", "0.5", "No", "", "", "Yes", "LTE001_ACC_00003", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "DEN", "SEA", "PRIORITY", "DGR", "NONSCR", "UN3373", "None", "1", "30", "CC", "None", "CART", "3373", "Biological substance, Category B", "650", "0.5", "No", "", "", "Yes", "LTE001_ACC_00003", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "DEN", "SEA", "PRIORITY", "DGR", "NONSCR", "UN1993", "None", "2", "65", "CC", "None", "CART", "1993", "Flammable liquid n.o.s. *", "351", "0.5", "No", "", "", "Yes", "LTE001_ACC_00003", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "DEN", "SEA", "PRIORITY", "DGR", "NONSCR", "UN1324", "None", "3", "99", "CC", "None", "CART", "1324", "Films, nitrocellulose base", "Y454", "0.5", "No", "", "", "Yes", "LTE001_ACC_00003", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "DEN", "SEA", "PRIORITY", "DGR", "NONSCR", "UN3481", "None", "1", "30", "CC", "None", "CART", "3481", "Lithium ion batteries contained in equipment", "967", "0.5", "No", "", "", "Yes", "LTE001_ACC_00003", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "DEN", "SEA", "PRIORITY", "DGR", "NONSCR", "UN3287", "None", "2", "65", "CC", "None", "CART", "3287", "Toxic liquid, inorganic n.o.s. *", "652", "0.5", "No", "", "", "Yes", "LTE001_ACC_00003", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "DEN", "SEA", "PRIORITY", "DGR", "NONSCR", "UN1369", "None", "3", "99", "CC", "None", "CART", "1369", "p-Nitrosodimethylaniline", "467", "0.5", "No", "", "", "Yes", "LTE001_ACC_00003", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "DFW", "SEA", "GENERAL", "None", "NONSCR", "None", "None", "13", "775", "PP", "CREDIT", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00004", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "DEN", "SEA", "PRIORITY", "None", "NONSCR", "None", "None", "8", "360", "PP", "CREDIT", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00004", null)]
        [NUnit.Framework.TestCaseAttribute("11377", "", "11377", "11377", "DEN", "SEA", "GOLDSTREAK", "None", "NONSCR", "None", "None", "2", "55", "PP", "CREDIT", "CART", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00004", null)]
        [NUnit.Framework.TestCaseAttribute("", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "Yes", "LTE001_ACC_00004", null)]
        public void LTE001_ACC_00002_CreateAnAWBInLTE001ForAnUnknownShipperOnARestrictedPaxFlight(
                    string agentCode, 
                    string unknownShipperCode, 
                    string shipperCode, 
                    string consigneeCode, 
                    string origin, 
                    string destination, 
                    string productCode, 
                    string sCC, 
                    string commodity, 
                    string shipmentDescription, 
                    string serviceCargoClass, 
                    string piece, 
                    string weight, 
                    string chargeType, 
                    string modeOfPayment, 
                    string cartType, 
                    string uNID, 
                    string properShipmentName, 
                    string packingInstruction, 
                    string netQtyPerPkg, 
                    string reportableQnty, 
                    string updatedValue, 
                    string ratedCustomer, 
                    string execute, 
                    string tags, 
                    string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "LTE001",
                    "LTE001_ACC_00002",
                    "smoke",
                    "DataSource:../TestData/LTE001_CreateShipment_TestData.xlsx",
                    "DataSet:LTE001_ACC_00001"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("AgentCode", agentCode);
            argumentsOfScenario.Add("UnknownShipperCode", unknownShipperCode);
            argumentsOfScenario.Add("ShipperCode", shipperCode);
            argumentsOfScenario.Add("ConsigneeCode", consigneeCode);
            argumentsOfScenario.Add("Origin", origin);
            argumentsOfScenario.Add("Destination", destination);
            argumentsOfScenario.Add("ProductCode", productCode);
            argumentsOfScenario.Add("SCC", sCC);
            argumentsOfScenario.Add("Commodity", commodity);
            argumentsOfScenario.Add("ShipmentDescription", shipmentDescription);
            argumentsOfScenario.Add("ServiceCargoClass", serviceCargoClass);
            argumentsOfScenario.Add("Piece", piece);
            argumentsOfScenario.Add("Weight", weight);
            argumentsOfScenario.Add("ChargeType", chargeType);
            argumentsOfScenario.Add("ModeOfPayment", modeOfPayment);
            argumentsOfScenario.Add("cartType", cartType);
            argumentsOfScenario.Add("UNID", uNID);
            argumentsOfScenario.Add("ProperShipmentName", properShipmentName);
            argumentsOfScenario.Add("PackingInstruction", packingInstruction);
            argumentsOfScenario.Add("NetQtyPerPkg", netQtyPerPkg);
            argumentsOfScenario.Add("ReportableQnty", reportableQnty);
            argumentsOfScenario.Add("UpdatedValue", updatedValue);
            argumentsOfScenario.Add("RatedCustomer", ratedCustomer);
            argumentsOfScenario.Add("Execute", execute);
            argumentsOfScenario.Add("Tags", tags);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("LTE001_ACC_00002_Create an AWB in LTE001 for an unknown shipper on a restricted p" +
                    "ax flight", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 30
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 31
 testRunner.Given(string.Format("User wants to execute the example \"{0}\" for the scenario \"{1}\"", execute, tags), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 32
 testRunner.When(string.Format("User switches station if BaseStation other than \"{0}\"", origin), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 33
 testRunner.And("User enters the screen name as \'LTE001\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 34
 testRunner.Then("User enters into the  iCargo \'Create Shipment\' page successfully", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 35
 testRunner.When("user clicks on the List button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 36
 testRunner.And(string.Format("User enters the Participant details with AgentCode \"{0}\",Unknown ShipperCode \"{1}" +
                            "\", ConsigneeCode \"{2}\"", agentCode, unknownShipperCode, consigneeCode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 37
 testRunner.And("User clicks on the ContinueParticipant button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 38
 testRunner.And("User enters the Certificate details", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 39
 testRunner.And("User clicks on the ContinueCertificate button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 40
 testRunner.And(string.Format("User enters the Shipment details with Origin \"{0}\", Destination \"{1}\", ProductCod" +
                            "e \"{2}\", SCCCode \"{3}\", Commodity \"{4}\", ShipmentDescription\"{5}\", ServiceCargoC" +
                            "lass \"{6}\", Piece \"{7}\", Weight \"{8}\"", origin, destination, productCode, sCC, commodity, shipmentDescription, serviceCargoClass, piece, weight), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 41
 testRunner.And("User clicks on the ContinueShipment button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 42
 testRunner.And("User clicks on the Select Flight Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 43
 testRunner.And("User selects an \"Combination\" flight", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 44
 testRunner.And("User clicks on the ContinueFlightDetails button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 45
 testRunner.And(string.Format("User enters the Charge details with ChargeType \"{0}\" and ModeOfPayment \"{1}\"", chargeType, modeOfPayment), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 46
 testRunner.And("User clicks on the CalculateCharges button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 47
 testRunner.And("User clicks on the ContinueChargeDetails button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 48
 testRunner.And("User enters the Acceptance details", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 49
 testRunner.And("User clicks on the ContinueAcceptanceDetails button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 50
 testRunner.And("User clicks on the ContinueScreeningDetails button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 51
 testRunner.And("User checks the AWB_Verified checkbox", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 52
 testRunner.And("User saves the shipment details validate error message as \"The Shipper does not h" +
                        "ave a Valid Certificate Type\" and capture AWB number", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
