name: main

on:
  push:
    tags:
      - HelloTestingDoesnoTMatter
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2019

    

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0' 
          dotnet-install-dir: /path/to/install/dir
          dotnet-install-arguments: '--channel LTS --install-dir /path/to/install/dir --no-path'
          
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Run tests by tag
        run: dotnet test --filter TestCategory=CAP018
        
